/** Verify the packaged Client factory in a browser with deterministic local Host responses. */
import assert from 'node:assert/strict'
import { createServer } from 'node:http'
import { readFile, mkdir } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { parseArgs } from 'node:util'
import { root, workspace } from './runtime.mjs'
const { values } = parseArgs({ options: { workspace: { type: 'string' } } })
const target = workspace(values.workspace)
const webRequire = createRequire(join(target, 'apps/web/package.json'))
const reactRequire = createRequire(join(target, 'packages/client/ui-renderer/package.json'))
const { chromium } = webRequire('playwright')
const files = new Map([
  ['/', join(root, 'tests/client-fixture.html')], ['/plugin.js', join(root, 'runtime/client/client.js')],
  ['/react.js', join(dirname(reactRequire.resolve('react/package.json')), 'umd/react.development.js')],
  ['/react-dom.js', join(dirname(webRequire.resolve('react-dom/package.json')), 'umd/react-dom.development.js')],
])
const server = createServer(async (req, res) => {
  const file = files.get(req.url)
  if (!file) { res.writeHead(404); res.end(); return }
  try { res.setHeader('content-type', req.url === '/' ? 'text/html; charset=utf-8' : 'text/javascript'); res.end(await readFile(file)) }
  catch { res.writeHead(500); res.end() }
})
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
let browser
try {
  try { browser = await chromium.launch({ headless: true }) }
  catch { browser = await chromium.launch({ channel: 'msedge', headless: true }) }
  const page = await browser.newPage({ viewport: { width: 1080, height: 1000 } })
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  const origin = `http://127.0.0.1:${server.address().port}`
  await page.goto(origin)
  const alias = page.getByPlaceholder('选择或输入，如 harness-lan')
  await alias.waitFor()
  await page.waitForFunction(() => document.querySelector('input[placeholder="选择或输入，如 harness-lan"]')?.value === 'harness-lan')
  assert.equal(await page.locator('input:visible').count(), 3)
  const aliases = page.getByRole('listbox', { name: '已有 SSH 连接', exact: true })
  const aliasSearch = page.getByRole('searchbox', { name: '搜索 SSH 别名', exact: true })
  const targets = page.getByRole('listbox', { name: '已保存目标', exact: true })
  const targetSearch = page.getByRole('searchbox', { name: '搜索目标名称、SSH 别名或工作区', exact: true })
  assert.equal(await aliases.inputValue(), 'harness-lan')
  await page.evaluate(() => { window.fixture.aliases = ['harness-lan', 'harness-wan', 'lab-box'] })
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('select[aria-label="已有 SSH 连接"]')?.options.length === 4)
  await aliasSearch.fill(' WAN ')
  assert.deepEqual(await aliases.locator('option').allTextContents(), ['请选择 SSH 别名', 'harness-wan'])
  await aliasSearch.press('Enter')
  assert.equal(await page.evaluate(() => window.fixture.calls), 0)
  await aliases.selectOption('harness-wan')
  assert.equal(await alias.inputValue(), 'harness-wan')
  await aliasSearch.fill('no-such-alias')
  await page.getByRole('status').filter({ hasText: '没有匹配的连接' }).waitFor()
  assert.equal(await alias.inputValue(), 'harness-wan')
  await aliasSearch.fill('')
  await aliases.selectOption('lab-box')
  await aliases.press('ArrowUp')
  assert.equal(await alias.inputValue(), 'harness-wan')
  await aliases.press('Enter')
  assert.equal(await page.evaluate(() => window.fixture.calls), 0)
  await mkdir(join(root, 'out/verification'), { recursive: true })
  await page.screenshot({ path: join(root, 'out/verification/searchable-connections.png'), fullPage: true })
  await aliases.selectOption('harness-lan')
  const help = page.getByRole('button', { name: '查看帮助: SSH 别名', exact: true })
  assert.equal(await help.getAttribute('aria-expanded'), 'false')
  await help.click()
  assert.equal(await help.getAttribute('aria-expanded'), 'true')
  assert.match(await page.getByRole('note').filter({ hasText: '用户名、地址、密钥和跳板机' }).innerText(), /无需重复填写/u)
  await help.press('Escape')
  assert.equal(await help.getAttribute('aria-expanded'), 'false')
  const shape = await help.evaluate(element => ({ radius: getComputedStyle(element).borderRadius, width: element.clientWidth, height: element.clientHeight }))
  assert.equal(shape.radius, '50%'); assert.equal(shape.width, shape.height)
  await page.getByText('高级选项', { exact: true }).click()
  assert.equal(await page.locator('input:visible').count(), 4)
  await page.locator('details input:visible').fill('team')
  await page.getByText('高级选项', { exact: true }).click()
  await mkdir(join(root, 'out/verification'), { recursive: true })
  await page.screenshot({ path: join(root, 'out/verification/quick-connection.png'), fullPage: true })
  await help.click()
  await page.screenshot({ path: join(root, 'out/verification/click-help.png'), fullPage: true })
  await help.click()
  await page.evaluate(() => { window.fixture.delay = 150 })
  await page.getByRole('button', { name: '一键连接', exact: true }).dblclick()
  assert.equal(await aliases.isDisabled(), true)
  assert.equal(await aliasSearch.isDisabled(), true)
  await page.getByRole('heading', { name: '连接状态: 已连接', exact: true }).waitFor()
  assert.equal(await page.evaluate(() => window.fixture.calls), 1)
  assert.equal(await page.evaluate(() => window.fixture.opens), 0)
  assert.equal(await targets.inputValue(), 'auto-id')
  assert.equal(await page.evaluate(() => window.fixture.targets[0].instanceKey), 'team')
  await page.getByRole('button', { name: '打开远程工作区', exact: true }).click()
  await page.getByRole('alert').filter({ hasText: '请先选择一个本机会话' }).waitFor()
  assert.equal(await page.evaluate(() => window.fixture.tickets), 0)
  await page.evaluate(() => { window.fixture.session = true })
  await page.getByRole('button', { name: '打开远程工作区', exact: true }).click()
  await page.waitForFunction(() => window.fixture.opens === 1, undefined, { timeout: 3000 })
  assert.equal(await page.evaluate(() => window.fixture.panel), null)
  assert.equal(await page.evaluate(() => window.fixture.openedSession), 'session-a')
  assert.equal(await page.evaluate(() => window.fixture.openedUrl), 'http://127.0.0.1/example-ticket')
  await page.evaluate(() => { window.fixture.panel = 'remote-workspace'; window.fixture.browserFailure = 'Browser type unavailable' })
  await page.getByRole('button', { name: '打开远程工作区', exact: true }).click()
  await page.getByRole('alert').filter({ hasText: 'Browser type unavailable' }).waitFor()
  assert.equal(await page.evaluate(() => window.fixture.panel), 'remote-workspace')
  await page.evaluate(() => { window.fixture.browserFailure = ''; window.fixture.ticketDelay = 150 })
  await page.getByRole('button', { name: '打开远程工作区', exact: true }).click()
  await page.waitForFunction(() => window.fixture.tickets === 3)
  await page.evaluate(() => { window.fixture.sessionId = 'session-b' })
  await page.getByRole('alert').filter({ hasText: '本机会话已切换' }).waitFor()
  assert.equal(await page.evaluate(() => window.fixture.opens), 1)
  await page.evaluate(() => { window.fixture.sessionId = 'session-a'; window.fixture.ticketDelay = 0 })
  await page.screenshot({ path: join(root, 'out/verification/connected.png'), fullPage: true })
  await page.getByRole('button', { name: '断开', exact: true }).click()
  await page.evaluate(() => {
    window.fixture.targets.push({ ...window.fixture.targets[0], id: 'dev-id', name: '开发服务器',
      profile: 'dev', workspaceHint: '/srv/Design-Workspace',
      endpoints: [{ id: 'tcp', kind: 'frp-tcp', sshAlias: 'dev-ssh' }] });
  })
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await targetSearch.fill(' DESIGN-WORKSPACE ')
  assert.deepEqual(await targets.locator('option').allTextContents(), ['新建目标', '开发服务器 · dev-ssh'])
  await targets.selectOption('dev-id')
  assert.equal(await page.getByRole('combobox').inputValue(), 'tcp')
  assert.equal(await page.evaluate(() => window.fixture.calls), 1)
  await targetSearch.fill('开发服务器')
  assert.equal(await targets.inputValue(), 'dev-id')
  await targetSearch.fill('dev-ssh')
  assert.equal(await targets.inputValue(), 'dev-id')
  await targetSearch.fill('nothing-matches')
  await page.getByRole('status').filter({ hasText: '没有匹配的连接' }).waitFor()
  await page.getByRole('status').filter({ hasText: '当前目标: 开发服务器 · dev-ssh' }).waitFor()
  assert.equal(await page.getByRole('combobox').inputValue(), 'tcp')
  await targetSearch.fill('')
  await targets.selectOption('')
  assert.equal(await page.getByRole('combobox').inputValue(), '')
  assert.equal(await page.getByRole('button', { name: '连接', exact: true }).isDisabled(), true)
  await targets.selectOption('auto-id')
  await page.evaluate(() => { window.fixture.targets = window.fixture.targets.filter(target => target.id === 'auto-id') })
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await page.getByText('手动配置目标', { exact: true }).click()
  await page.getByRole('button', { name: '查看帮助: 远端 Web 端口', exact: true }).click()
  await page.getByRole('note').filter({ hasText: '此处不是 SSH 端口或 frp 端口' }).waitFor()
  await page.getByText('手动配置目标', { exact: true }).click()
  await page.getByRole('button', { name: '一键连接', exact: true }).click()
  await page.waitForFunction(() => window.fixture.opens === 2)
  await page.getByRole('button', { name: '断开', exact: true }).click()
  await page.evaluate(() => { window.fixture.failure = 'remote-workspace: SSH_HOST_KEY' })
  await page.getByRole('button', { name: '一键连接', exact: true }).click()
  await page.getByRole('alert').filter({ hasText: 'SSH 主机密钥尚未确认或已变化' }).waitFor()
  await page.evaluate(() => { window.fixture.failure = 'remote-workspace: SSH_HELPER' })
  await page.getByRole('button', { name: '一键连接', exact: true }).click()
  await page.getByRole('alert').filter({ hasText: '远端 helper 缺失、不可执行或配置不正确' }).waitFor()
  await page.evaluate(() => { window.fixture.failure = ''; window.fixture.failAliases = true })
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await page.getByRole('status').filter({ hasText: '暂时无法读取 SSH 别名' }).waitFor()
  await alias.fill('manual-alias')
  await page.getByRole('button', { name: '一键连接', exact: true }).click()
  await page.waitForFunction(() => window.fixture.opens === 3)
  await page.getByRole('button', { name: '断开', exact: true }).click()
  await page.evaluate(() => { window.fixture.failAliases = false; window.fixture.aliases = [] })
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await page.getByRole('status').filter({ hasText: '尚未找到已有 SSH 别名' }).waitFor()
  assert.equal(await alias.inputValue(), 'manual-alias')
  await page.evaluate(() => { window.fixture.aliases = ['harness-lan', 'harness-wan', 'lab-box'] })
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await aliasSearch.fill('wan')
  await page.screenshot({ path: join(root, 'out/verification/searchable-connections-narrow.png'), fullPage: true })
  await aliasSearch.fill('')
  await page.screenshot({ path: join(root, 'out/verification/narrow-connection.png'), fullPage: true })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  await page.evaluate(() => {
    window.fixture.targetName = window.fixture.targets[0].name;
    window.fixture.targets[0].name = '很长的连接名称'.repeat(50);
    window.fixture.aliases.push('long-alias-'.repeat(11));
  })
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  await page.evaluate(() => {
    window.fixture.targets[0].name = window.fixture.targetName;
    window.fixture.aliases.pop();
  })
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await page.evaluate(() => { window.fixture.missingRoutes = true })
  await page.getByRole('button', { name: '一键连接', exact: true }).click()
  const restart = page.getByRole('alert').filter({ hasText: '请完全退出 DeepSeek Harness（包括托盘）后重新打开' })
  await restart.waitFor({ timeout: 3000 })
  assert.equal(await page.getByRole('button', { name: '一键连接', exact: true }).isDisabled(), true)
  assert.equal(await page.getByRole('button', { name: '连接', exact: true }).isDisabled(), false)
  const oldHostCalls = await page.evaluate(() => window.fixture.calls)
  await alias.press('Enter')
  assert.equal(await page.evaluate(() => window.fixture.calls), oldHostCalls)
  await page.screenshot({ path: join(root, 'out/verification/restart-required.png'), fullPage: true })
  await page.evaluate(() => { window.fixture.missingRoutes = false; window.fixture.failAliases = false })
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await restart.waitFor({ state: 'hidden' })
  assert.equal(await page.getByRole('button', { name: '一键连接', exact: true }).isEnabled(), true)
  await page.evaluate(() => { window.fixture.missingRoutes = true })
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await restart.waitFor({ timeout: 3000 })
  assert.equal(await page.getByRole('button', { name: '一键连接', exact: true }).isDisabled(), true)
  await page.evaluate(() => { window.fixture.missingRoutes = false; window.fixture.failure = 'unrelated resource: HTTP 404' })
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await restart.waitFor({ state: 'hidden' })
  await page.getByRole('button', { name: '一键连接', exact: true }).click()
  await page.getByRole('alert').filter({ hasText: 'unrelated resource: HTTP 404' }).waitFor()
  assert.equal(await page.getByRole('button', { name: '一键连接', exact: true }).isEnabled(), true)
  assert.deepEqual(errors, [])
  console.log('PASS packaged Client: searchable SSH and saved-target lists, keyboard selection without connection, empty and no-match states, selection preservation, manual alias fallback, circular help, duplicate suppression, selected-session opening, error recovery, narrow layout and stale Host route recovery')
} finally {
  await browser?.close()
  await new Promise(resolve => server.close(resolve))
}
