/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _harness_remote_controller_remoteWorkspace_connect_parameter_0$schema$value
const _harness_remote_controller_remoteWorkspace_connect_parameter_0$schema = () => (_harness_remote_controller_remoteWorkspace_connect_parameter_0$schema$value ??= z.string())
let _harness_remote_controller_remoteWorkspace_connect_parameter_1$schema$value
const _harness_remote_controller_remoteWorkspace_connect_parameter_1$schema = () => (_harness_remote_controller_remoteWorkspace_connect_parameter_1$schema$value ??= z.string())
let _harness_remote_controller_remoteWorkspace_connect_parameter_2$schema$value
const _harness_remote_controller_remoteWorkspace_connect_parameter_2$schema = () => (_harness_remote_controller_remoteWorkspace_connect_parameter_2$schema$value ??= z.string())
let _harness_remote_controller_remoteWorkspace_connect_result$schema$value
const _harness_remote_controller_remoteWorkspace_connect_result$schema = () => (_harness_remote_controller_remoteWorkspace_connect_result$schema$value ??= z.object({
  'phase': z.union([z.literal("error"), z.literal("idle"), z.literal("ssh-auth"), z.literal("discovering"), z.literal("forwarding"), z.literal("authenticating"), z.literal("app-ready"), z.literal("disconnected"), z.literal("reconnecting"), z.literal("identity-mismatch"), z.literal("auth-required")]).readonly(),
  'connectionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'targetId': z.string().readonly().optional(),
  'endpointId': z.string().readonly().optional(),
  'hostName': z.string().readonly().optional(),
  'instanceId': z.string().readonly().optional(),
  'bootId': z.string().readonly().optional(),
  'profile': z.string().readonly().optional(),
  'workspaceHint': z.string().readonly().optional(),
  'generation': z.number().readonly(),
  'reason': z.string().readonly().optional(),
}))
let _harness_remote_controller_remoteWorkspace_createOpenTicket_parameter_0$schema$value
const _harness_remote_controller_remoteWorkspace_createOpenTicket_parameter_0$schema = () => (_harness_remote_controller_remoteWorkspace_createOpenTicket_parameter_0$schema$value ??= z.string())
let _harness_remote_controller_remoteWorkspace_createOpenTicket_result$schema$value
const _harness_remote_controller_remoteWorkspace_createOpenTicket_result$schema = () => (_harness_remote_controller_remoteWorkspace_createOpenTicket_result$schema$value ??= z.string())
let _harness_remote_controller_remoteWorkspace_disconnect_parameter_0$schema$value
const _harness_remote_controller_remoteWorkspace_disconnect_parameter_0$schema = () => (_harness_remote_controller_remoteWorkspace_disconnect_parameter_0$schema$value ??= z.string())
let _harness_remote_controller_remoteWorkspace_disconnect_result$schema$value
const _harness_remote_controller_remoteWorkspace_disconnect_result$schema = () => (_harness_remote_controller_remoteWorkspace_disconnect_result$schema$value ??= z.object({
  'phase': z.union([z.literal("error"), z.literal("idle"), z.literal("ssh-auth"), z.literal("discovering"), z.literal("forwarding"), z.literal("authenticating"), z.literal("app-ready"), z.literal("disconnected"), z.literal("reconnecting"), z.literal("identity-mismatch"), z.literal("auth-required")]).readonly(),
  'connectionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'targetId': z.string().readonly().optional(),
  'endpointId': z.string().readonly().optional(),
  'hostName': z.string().readonly().optional(),
  'instanceId': z.string().readonly().optional(),
  'bootId': z.string().readonly().optional(),
  'profile': z.string().readonly().optional(),
  'workspaceHint': z.string().readonly().optional(),
  'generation': z.number().readonly(),
  'reason': z.string().readonly().optional(),
}))
let _harness_remote_controller_remoteWorkspace_getState_result$schema$value
const _harness_remote_controller_remoteWorkspace_getState_result$schema = () => (_harness_remote_controller_remoteWorkspace_getState_result$schema$value ??= z.object({
  'phase': z.union([z.literal("error"), z.literal("idle"), z.literal("ssh-auth"), z.literal("discovering"), z.literal("forwarding"), z.literal("authenticating"), z.literal("app-ready"), z.literal("disconnected"), z.literal("reconnecting"), z.literal("identity-mismatch"), z.literal("auth-required")]).readonly(),
  'connectionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'targetId': z.string().readonly().optional(),
  'endpointId': z.string().readonly().optional(),
  'hostName': z.string().readonly().optional(),
  'instanceId': z.string().readonly().optional(),
  'bootId': z.string().readonly().optional(),
  'profile': z.string().readonly().optional(),
  'workspaceHint': z.string().readonly().optional(),
  'generation': z.number().readonly(),
  'reason': z.string().readonly().optional(),
}))
let _harness_remote_controller_remoteWorkspace_listTargets_result$schema$value
const _harness_remote_controller_remoteWorkspace_listTargets_result$schema = () => (_harness_remote_controller_remoteWorkspace_listTargets_result$schema$value ??= z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'instanceKey': z.string().readonly(),
  'instanceId': z.string().readonly(),
  'profile': z.string().readonly(),
  'workspaceHint': z.string().readonly(),
  'remotePort': z.number().readonly(),
  'endpoints': z.array(z.object({
  'id': z.string().readonly(),
  'kind': z.union([z.literal("lan"), z.literal("frp-tcp"), z.literal("stcp")]).readonly(),
  'sshAlias': z.string().readonly(),
})).readonly(),
})))
let _harness_remote_controller_remoteWorkspace_saveTarget_parameter_0$schema$value
const _harness_remote_controller_remoteWorkspace_saveTarget_parameter_0$schema = () => (_harness_remote_controller_remoteWorkspace_saveTarget_parameter_0$schema$value ??= z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'instanceKey': z.string().readonly(),
  'instanceId': z.string().readonly(),
  'profile': z.string().readonly(),
  'workspaceHint': z.string().readonly(),
  'remotePort': z.number().readonly(),
  'endpoints': z.array(z.object({
  'id': z.string().readonly(),
  'kind': z.union([z.literal("lan"), z.literal("frp-tcp"), z.literal("stcp")]).readonly(),
  'sshAlias': z.string().readonly(),
})).readonly(),
}))
let _harness_remote_controller_remoteWorkspace_saveTarget_result$schema$value
const _harness_remote_controller_remoteWorkspace_saveTarget_result$schema = () => (_harness_remote_controller_remoteWorkspace_saveTarget_result$schema$value ??= z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'instanceKey': z.string().readonly(),
  'instanceId': z.string().readonly(),
  'profile': z.string().readonly(),
  'workspaceHint': z.string().readonly(),
  'remotePort': z.number().readonly(),
  'endpoints': z.array(z.object({
  'id': z.string().readonly(),
  'kind': z.union([z.literal("lan"), z.literal("frp-tcp"), z.literal("stcp")]).readonly(),
  'sshAlias': z.string().readonly(),
})).readonly(),
})))
let _harness_remote_controller_remoteWorkspace_watch_result$schema$value
const _harness_remote_controller_remoteWorkspace_watch_result$schema = () => (_harness_remote_controller_remoteWorkspace_watch_result$schema$value ??= z.object({
  'phase': z.union([z.literal("error"), z.literal("idle"), z.literal("ssh-auth"), z.literal("discovering"), z.literal("forwarding"), z.literal("authenticating"), z.literal("app-ready"), z.literal("disconnected"), z.literal("reconnecting"), z.literal("identity-mismatch"), z.literal("auth-required")]).readonly(),
  'connectionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'targetId': z.string().readonly().optional(),
  'endpointId': z.string().readonly().optional(),
  'hostName': z.string().readonly().optional(),
  'instanceId': z.string().readonly().optional(),
  'bootId': z.string().readonly().optional(),
  'profile': z.string().readonly().optional(),
  'workspaceHint': z.string().readonly().optional(),
  'generation': z.number().readonly(),
  'reason': z.string().readonly().optional(),
}))

export const TYPERT = {
  package: 'dsh-win-ssh-controller-source',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-win-ssh-controller-source#remoteWorkspace/connect',
      service: 'remoteWorkspace',
      namespace: 'remoteWorkspace',
      method: 'connect',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'targetId',
          wire: 'targetId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-win-ssh-controller-source#remoteWorkspace/connect:targetId',
            create: _harness_remote_controller_remoteWorkspace_connect_parameter_0$schema,
          },
        },
        {
          name: 'endpointId',
          wire: 'endpointId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-win-ssh-controller-source#remoteWorkspace/connect:endpointId',
            create: _harness_remote_controller_remoteWorkspace_connect_parameter_1$schema,
          },
        },
        {
          name: 'operationId',
          wire: 'operationId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-win-ssh-controller-source#remoteWorkspace/connect:operationId',
            create: _harness_remote_controller_remoteWorkspace_connect_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-win-ssh-controller-source/types#RemoteSnapshot',
        create: _harness_remote_controller_remoteWorkspace_connect_result$schema,
      },
      sourceLocation: {"file":"packages/remote/controller/src/index.ts","line":64,"column":3},
    },
    {
      id: 'dsh-win-ssh-controller-source#remoteWorkspace/createOpenTicket',
      service: 'remoteWorkspace',
      namespace: 'remoteWorkspace',
      method: 'createOpenTicket',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'connectionId',
          wire: 'connectionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-win-ssh-controller-source#remoteWorkspace/createOpenTicket:connectionId',
            create: _harness_remote_controller_remoteWorkspace_createOpenTicket_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-win-ssh-controller-source#remoteWorkspace/createOpenTicket:result',
        create: _harness_remote_controller_remoteWorkspace_createOpenTicket_result$schema,
      },
      sourceLocation: {"file":"packages/remote/controller/src/index.ts","line":89,"column":3},
    },
    {
      id: 'dsh-win-ssh-controller-source#remoteWorkspace/disconnect',
      service: 'remoteWorkspace',
      namespace: 'remoteWorkspace',
      method: 'disconnect',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'connectionId',
          wire: 'connectionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-win-ssh-controller-source#remoteWorkspace/disconnect:connectionId',
            create: _harness_remote_controller_remoteWorkspace_disconnect_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-win-ssh-controller-source/types#RemoteSnapshot',
        create: _harness_remote_controller_remoteWorkspace_disconnect_result$schema,
      },
      sourceLocation: {"file":"packages/remote/controller/src/index.ts","line":81,"column":3},
    },
    {
      id: 'dsh-win-ssh-controller-source#remoteWorkspace/getState',
      service: 'remoteWorkspace',
      namespace: 'remoteWorkspace',
      method: 'getState',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-win-ssh-controller-source/types#RemoteSnapshot',
        create: _harness_remote_controller_remoteWorkspace_getState_result$schema,
      },
      sourceLocation: {"file":"packages/remote/controller/src/index.ts","line":73,"column":3},
    },
    {
      id: 'dsh-win-ssh-controller-source#remoteWorkspace/listTargets',
      service: 'remoteWorkspace',
      namespace: 'remoteWorkspace',
      method: 'listTargets',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-win-ssh-controller-source#remoteWorkspace/listTargets:result',
        create: _harness_remote_controller_remoteWorkspace_listTargets_result$schema,
      },
      sourceLocation: {"file":"packages/remote/controller/src/index.ts","line":46,"column":3},
    },
    {
      id: 'dsh-win-ssh-controller-source#remoteWorkspace/saveTarget',
      service: 'remoteWorkspace',
      namespace: 'remoteWorkspace',
      method: 'saveTarget',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'target',
          wire: 'target',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-win-ssh-controller-source/types#RemoteTarget',
            create: _harness_remote_controller_remoteWorkspace_saveTarget_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-win-ssh-controller-source#remoteWorkspace/saveTarget:result',
        create: _harness_remote_controller_remoteWorkspace_saveTarget_result$schema,
      },
      sourceLocation: {"file":"packages/remote/controller/src/index.ts","line":54,"column":3},
    },
    {
      id: 'dsh-win-ssh-controller-source#remoteWorkspace/watch',
      service: 'remoteWorkspace',
      namespace: 'remoteWorkspace',
      method: 'watch',
      mode: 'stream',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-win-ssh-controller-source/types#RemoteSnapshot',
        create: _harness_remote_controller_remoteWorkspace_watch_result$schema,
      },
      sourceLocation: {"file":"packages/remote/controller/src/index.ts","line":97,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Authenticated Remote methods for the local management page.",
        "summary": "Authenticated Remote methods for the local management page.",
        "tags": [],
        "jsDoc": "/** Authenticated Remote methods for the local management page. */",
        "key": "remoteWorkspace",
        "exportName": "default",
        "members": [
          {
            "kind": "method",
            "name": "listTargets",
            "signature": "@Remote listTargets(): Promise<RemoteTarget[]>",
            "summary": "Read configured remote attachment targets.",
            "jsDoc": "/**\n * Read configured remote attachment targets.\n * @returns all non-secret target records.\n */"
          },
          {
            "kind": "method",
            "name": "saveTarget",
            "signature": "@Remote saveTarget(target: RemoteTarget): Promise<RemoteTarget[]>",
            "summary": "Persist one complete target without credentials.",
            "jsDoc": "/**\n * Persist one complete target without credentials.\n * @param target - complete non-secret record.\n * @returns saved target records.\n */"
          },
          {
            "kind": "method",
            "name": "connect",
            "signature": "@Remote connect(targetId: string, endpointId: string, operationId: string): Promise<RemoteSnapshot>",
            "summary": "Attach one target over a reviewed SSH alias.",
            "jsDoc": "/**\n * Attach one target over a reviewed SSH alias.\n * @param targetId - stable target id.\n * @param endpointId - chosen LAN, TCP, or STCP endpoint.\n * @param operationId - idempotency key for this connect intent.\n * @returns connection state after authentication and event readiness.\n */"
          },
          {
            "kind": "method",
            "name": "getState",
            "signature": "@Remote getState(): RemoteSnapshot",
            "summary": "Read the local attachment state.",
            "jsDoc": "/**\n * Read the local attachment state.\n * @returns current local connection state without credentials.\n */"
          },
          {
            "kind": "method",
            "name": "disconnect",
            "signature": "@Remote disconnect(connectionId: string): Promise<RemoteSnapshot>",
            "summary": "Release local resources owned by one attachment.",
            "jsDoc": "/**\n * Release local resources owned by one attachment.\n * @param connectionId - active local attachment.\n * @returns new state.\n */"
          },
          {
            "kind": "method",
            "name": "createOpenTicket",
            "signature": "@Remote createOpenTicket(connectionId: string): string",
            "summary": "Issue a Browser ticket for the authenticated attachment.",
            "jsDoc": "/**\n * Issue a Browser ticket for the authenticated attachment.\n * @param connectionId - ready local attachment.\n * @returns one-use, short-lived local Browser URL.\n */"
          },
          {
            "kind": "method",
            "name": "watch",
            "signature": "@Remote({ mode: 'stream' }) watch(signal: AbortSignal): AsyncIterable<RemoteSnapshot>",
            "summary": "Observe attachment state until the caller cancels its stream.",
            "jsDoc": "/**\n * Observe attachment state until the caller cancels its stream.\n * @param signal - Remote stream lifetime.\n * @returns current state and later changes.\n */"
          }
        ],
        "types": [
          {
            "name": "RemoteEndpoint",
            "declaration": "export interface RemoteEndpoint {\n    readonly id: string;\n    readonly kind: 'lan' | 'frp-tcp' | 'stcp';\n    readonly sshAlias: string;\n}"
          },
          {
            "name": "RemotePhase",
            "declaration": "export type RemotePhase = 'idle' | 'ssh-auth' | 'discovering' | 'forwarding' | 'authenticating' | 'app-ready' | 'disconnected' | 'reconnecting' | 'identity-mismatch' | 'auth-required' | 'error';"
          },
          {
            "name": "RemoteSnapshot",
            "declaration": "export interface RemoteSnapshot {\n    readonly phase: RemotePhase;\n    readonly connectionId?: string | undefined;\n    readonly targetId?: string;\n    readonly endpointId?: string;\n    readonly hostName?: string;\n    readonly instanceId?: string;\n    readonly bootId?: string;\n    readonly profile?: string;\n    readonly workspaceHint?: string;\n    readonly generation: number;\n    readonly reason?: string;\n}"
          },
          {
            "name": "RemoteTarget",
            "declaration": "export interface RemoteTarget {\n    readonly id: string;\n    readonly name: string;\n    readonly instanceKey: string;\n    readonly instanceId: string;\n    readonly profile: string;\n    readonly workspaceHint: string;\n    readonly remotePort: number;\n    readonly endpoints: readonly RemoteEndpoint[];\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
