/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  RemoteStreamHandle,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { RemoteSnapshot, RemoteTarget } from 'dsh-win-ssh-controller-source/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$72656d6f7465576f726b7370616365 {
    connect: (targetId: string, endpointId: string, operationId: string) => Promise<RemoteResult<RemoteSnapshot>>
    createOpenTicket: (connectionId: string) => Promise<RemoteResult<string>>
    disconnect: (connectionId: string) => Promise<RemoteResult<RemoteSnapshot>>
    getState: () => Promise<RemoteResult<RemoteSnapshot>>
    listTargets: () => Promise<RemoteResult<RemoteTarget[]>>
    saveTarget: (target: RemoteTarget) => Promise<RemoteResult<RemoteTarget[]>>
    watch: (signal?: AbortSignal) => RemoteStreamHandle<RemoteSnapshot, never>
  }
  interface TypertRemoteMap {
    'remoteWorkspace/connect': (targetId: string, endpointId: string, operationId: string) => Promise<RemoteResult<RemoteSnapshot>>
    'remoteWorkspace/createOpenTicket': (connectionId: string) => Promise<RemoteResult<string>>
    'remoteWorkspace/disconnect': (connectionId: string) => Promise<RemoteResult<RemoteSnapshot>>
    'remoteWorkspace/getState': () => Promise<RemoteResult<RemoteSnapshot>>
    'remoteWorkspace/listTargets': () => Promise<RemoteResult<RemoteTarget[]>>
    'remoteWorkspace/saveTarget': (target: RemoteTarget) => Promise<RemoteResult<RemoteTarget[]>>
    'remoteWorkspace/watch': (signal?: AbortSignal) => RemoteStreamHandle<RemoteSnapshot, never>
  }
  interface TypertRemoteNamespaceMap {
    'remoteWorkspace': TypertRemoteNamespace$72656d6f7465576f726b7370616365
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
